### ISSUE TITLE
Can not download fullTraining_pkls.tar.gz

### ISSUE THREAD

**Issue by FredericBGA** [eliza-m/LRRpredictor_v1#4]
Hello

Even with `--no-check-certificate` flag the `fullTraining_pkls.tar.gz` file can not be downloaded.

The site `old.biochim.ro` seems to be offline.

**Comment by eliza-m** [comment]
Hi !
Thank you for noticing this. There seems to be a problem with the location where the files are being stored. If the hosting location is not resolved, I will return tomorrow with a different link for downloading the data.

Thank you and apologies for the inconvenience,
Eliza

**Comment by eliza-m** [comment]
Hi ! 
The issue seems to be resolved now. Please let me know if the problem persists.
Thank you again for noticing !
